spring:
  profiles:
    active: prod

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

  servlet:
    multipart:
      max-request-size: 30MB
      max-file-size: 30MB

logging:
  level:
    org.springframework.security: DEBUG
    org.hibernate.orm.jdbc.bind: trace

jwt:
  secret: ${JWT_SECRET_KEY}
  access-exp-time: ${JWT_ACCESS_EXP_TIME}
  refresh-exp-time: ${JWT_REFRESH_EXP_TIME}